#ifndef Engine_enum_h__
#define Engine_enum_h__

namespace Engine
{
	enum RESOURCE_TYPE { RESOURCE_STATIC, RESOURCE_DYNAMIC, RESOURCE_END };
	enum TEXTURE_TYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	enum ANGLE_TYPE { ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END };

	enum SPACE { LOCAL_SPACE, WORLD_SPACE, VIEW_SPACE, PROJECTION_SPACE };
	enum CAMERA_TYPE { CAMTYPE_PERSPECTIVE, CAMTYPE_ORTHOGRAPH, CAMTYPE_END };
}

#endif // Engine_enum_h__
